include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    # Enforcing trailing commas for better formatting and diffs
    require_trailing_commas: true
    # Additional rules for better code formatting
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    # Style rules
    always_put_control_body_on_new_line: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    # Disable some conflicting rules
    lines_longer_than_80_chars: false
