// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6Qye39T0eDjWgOPD9lW8wsjTb8J1N5A',
    appId: '1:983365340935:web:032e07e87f5e5700893fa2',
    messagingSenderId: '983365340935',
    projectId: 'flutter-projects-6c6dc',
    authDomain: 'flutter-projects-6c6dc.firebaseapp.com',
    storageBucket: 'flutter-projects-6c6dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6IwwWwZ3MFz5m7ggeMk4l62aBdv3-es',
    appId: '1:983365340935:android:c939fb7ee770a5b3893fa2',
    messagingSenderId: '983365340935',
    projectId: 'flutter-projects-6c6dc',
    storageBucket: 'flutter-projects-6c6dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1n-icdMRU3JKJAB4Cr55ToAIACr2ql9U',
    appId: '1:983365340935:ios:09f097a33d6635b1893fa2',
    messagingSenderId: '983365340935',
    projectId: 'flutter-projects-6c6dc',
    storageBucket: 'flutter-projects-6c6dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1n-icdMRU3JKJAB4Cr55ToAIACr2ql9U',
    appId: '1:983365340935:ios:09f097a33d6635b1893fa2',
    messagingSenderId: '983365340935',
    projectId: 'flutter-projects-6c6dc',
    storageBucket: 'flutter-projects-6c6dc.firebasestorage.app',
    iosBundleId: 'com.example.flutterPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ6Qye39T0eDjWgOPD9lW8wsjTb8J1N5A',
    appId: '1:983365340935:web:88d56846702663df893fa2',
    messagingSenderId: '983365340935',
    projectId: 'flutter-projects-6c6dc',
    authDomain: 'flutter-projects-6c6dc.firebaseapp.com',
    storageBucket: 'flutter-projects-6c6dc.firebasestorage.app',
  );
}
